name: E2E Tests
on: [pull_request]

jobs:
  e2e:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    # - name: Setup env
    #   run: ./setup.sh https://github.com/charmed-kubernetes/cluster-api-provider-juju.git https://github.com/charmed-kubernetes/cluster-api-control-plane-provider-charmed-k8s.git https://github.com/charmed-kubernetes/cluster-api-bootstrap-provider-charmed-k8s.git
    - name: Run tests
      shell: bash
      env:
        CREDENTIALS: ${{ secrets.CREDENTIALS_YAML }}
      run: |
          echo -n $CREDENTIALS | base64 -d > cert.der
      # run: ./run.sh 