name: Linting
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"

  lint:
    name: Lint
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    needs: 
      - call-inclusive-naming-check
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Tox
      run: pip install tox
    - name: Run lint 
      run: tox -e lint